<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <PackageId>AiDialSdk.Testing</PackageId>
        <Version>0.0.1-alpha.8</Version>
        <Authors>KlimTeam</Authors>
        <Description>Testing utilities for DIAL platform</Description>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>

        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>

        <DebugType>portable</DebugType>
        <DebugSymbols>true</DebugSymbols>

        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        
        <PackageProjectUrl>https://github.com/klimteam/ai-dial-sdk-testing</PackageProjectUrl>
        <RepositoryUrl>https://github.com/klimteam/ai-dial-sdk-testing</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    </ItemGroup>
    
    <ItemGroup>
        <PackageReference Include="AiDialSdk.Api" Version="0.0.1-alpha.4" />
        <PackageReference Include="Azure.AI.OpenAI" Version="2.8.0-beta.1" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.3" />
        <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.3.0" />
        <PackageReference Include="Moq" Version="4.20.72" />
    </ItemGroup>
</Project>
